# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[(b'housing', b'Housing Reviews'), (b'course', b'Housing Reviews'), (b'sagelist', b'SageBooks'), (b'twitter', b'Twitter')], max_length=100),
        ),
    ]
