# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityfeed', '0002_auto_20160930_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[(b'housing', b'Housing Reviews'), (b'course', b'Course Reviews'), (b'sagelist', b'SageBooks'), (b'twitter', b'Twitter')], max_length=100),
        ),
    ]
