# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0004_auto_20150518_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='position',
            name='committee',
            field=models.CharField(choices=[(b'senate', b'Senate'), (b'student', b'Student-Led Committee'), (b'faculty', b'Faculty-Led Committee')], default=b'senate', max_length=100),
        ),
    ]
