# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0003_userdata_subscribed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='subscribed_email',
            field=models.BooleanField(default=True),
        ),
    ]
