# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160322_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
