# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursereview_created_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set([('author', 'course', 'instructor')]),
        ),
    ]
