# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20160412_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='approachable_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='competency_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='difficulty_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='enthusiasm_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='lecturing_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='useful_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='work_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
