# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20160416_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approachable_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='competency_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enthusiasm_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturing_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='useful_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='approachable_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='competency_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='difficulty_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='enthusiasm_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='lecturing_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='useful_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
