# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20160903_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='approachable_rating',
            new_name='cached_approachable_rating',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='competency_rating',
            new_name='cached_competency_rating',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='difficulty_rating',
            new_name='cached_difficulty_rating',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='engagement_rating',
            new_name='cached_engagement_rating',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='enthusiasm_rating',
            new_name='cached_enthusiasm_rating',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='lecturing_rating',
            new_name='cached_lecturing_rating',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='rating',
            new_name='cached_rating',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='useful_rating',
            new_name='cached_useful_rating',
        ),
    ]
