# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20160904_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'A+'), (1, 'A'), (2, 'A-'), (3, 'B+'), (4, 'B'), (5, 'B-'), (6, 'C+'), (7, 'C'), (8, 'C-'), (9, 'D+'), (10, 'D'), (11, 'D-'), (12, 'F'), (13, 'P'), (14, 'NP'), (15, 'Other')], null=True),
        ),
    ]
