# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_featuringqueries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturingQueries',
            new_name='FeaturingQuery',
        ),
    ]
