# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_featuringquery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor')),
            ],
        ),
    ]
