# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_rmpinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmpinfo',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
        ),
    ]
