# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20161031_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmpinfo',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
