# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20161101_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='inclusivity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='inclusivity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='inclusivity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='cached_inclusivity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
