# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-10 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20170414_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='challenge_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='challenge_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='respect_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
