# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-17 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20170917_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='cached_challenge_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
