# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forum.Tag'),
        ),
    ]
