# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 10:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TextField()),
                ('feeling', models.TextField()),
                ('identity_related_comment', models.TextField(blank=True, null=True)),
                ('therapist_recommendation', models.TextField()),
                ('therapist_strategy', models.TextField()),
                ('created_ts', models.DateTimeField(default=datetime.datetime.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.CreateModel(
            name='SexualOrientation',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.Category')),
            ],
            bases=('mentalhealth.category',),
        ),
        migrations.AddField(
            model_name='mentalhealthreview',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalhealth.Therapist'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='insurances',
            field=models.ManyToManyField(to='mentalhealth.Insurance'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='qualifications',
            field=models.ManyToManyField(blank=True, null=True, to='mentalhealth.Qualification'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='specialties',
            field=models.ManyToManyField(to='mentalhealth.Specialty'),
        ),
        migrations.AddField(
            model_name='mentalhealthreview',
            name='ethnicity',
            field=models.ManyToManyField(to='mentalhealth.Ethnicity'),
        ),
        migrations.AddField(
            model_name='mentalhealthreview',
            name='gender',
            field=models.ManyToManyField(to='mentalhealth.Gender'),
        ),
        migrations.AddField(
            model_name='mentalhealthreview',
            name='identity',
            field=models.ManyToManyField(to='mentalhealth.Identity'),
        ),
        migrations.AddField(
            model_name='mentalhealthreview',
            name='reasons',
            field=models.ManyToManyField(to='mentalhealth.Specialty'),
        ),
        migrations.AddField(
            model_name='mentalhealthreview',
            name='sexual_orientation',
            field=models.ManyToManyField(to='mentalhealth.SexualOrientation'),
        ),
        migrations.AddField(
            model_name='mentalhealthreview',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='mentalhealth.Tag'),
        ),
    ]
