# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0003_auto_20161216_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthreview',
            name='ethnicity',
            field=models.ManyToManyField(blank=True, related_name='ethnicities', to='mentalhealth.Ethnicity'),
        ),
        migrations.AlterField(
            model_name='mentalhealthreview',
            name='gender',
            field=models.ManyToManyField(blank=True, related_name='genders', to='mentalhealth.Gender'),
        ),
        migrations.AlterField(
            model_name='mentalhealthreview',
            name='identity',
            field=models.ManyToManyField(blank=True, related_name='identities', to='mentalhealth.Identity'),
        ),
        migrations.AlterField(
            model_name='mentalhealthreview',
            name='sexual_orientation',
            field=models.ManyToManyField(blank=True, related_name='orientations', to='mentalhealth.SexualOrientation'),
        ),
        migrations.AlterField(
            model_name='mentalhealthreview',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mentalhealth.Therapist'),
        ),
    ]
