# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0003_auto_20161216_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='image',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='mentalhealthreview',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mentalhealth.Therapist'),
        ),
    ]
