# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-01 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0005_auto_20161216_1500'),
        ('mentalhealth', '0004_auto_20161216_1503'),
    ]

    operations = [
    ]