# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthreview',
            name='created_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
