# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0008_auto_20170123_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ('name',)},
        ),
    ]
