# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('station', models.CharField(max_length=1024)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dining_hall', models.CharField(choices=[(b'frank', b'Frank'), (b'frary', b'Frary'), (b'oldenborg', b'Oldenborg'), (b'scripps', b'Scripps'), (b'mudd', b'Mudd'), (b'cmc', b'CMC'), (b'pitzer', b'Pitzer')], max_length=1024)),
                ('meal', models.CharField(choices=[(b'breakfast', b'Breakfast'), (b'lunch', b'Lunch'), (b'dinner', b'Dinner'), (b'brunch', b'Brunch')], max_length=1024)),
                ('day', models.CharField(choices=[(b'mon', b'Monday'), (b'tue', b'Tuesday'), (b'wed', b'Wednesday'), (b'thu', b'Thursday'), (b'fri', b'Friday'), (b'sat', b'Saturday'), (b'sun', b'Sunday')], max_length=1024)),
                ('food_items', models.ManyToManyField(to='menu.Item')),
            ],
            options={
                'ordering': ('day', 'dining_hall', 'meal'),
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
