# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20160507_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_items',
        ),
        migrations.AddField(
            model_name='menu',
            name='food_items',
            field=models.ManyToManyField(to='menu.Item'),
        ),
    ]
