# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20160513_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='station',
            field=models.CharField(default=b'', max_length=1024),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.CharField(choices=[(b'mon', b'Monday'), (b'tue', b'Tuesday'), (b'wed', b'Wednesday'), (b'thu', b'Thursday'), (b'fri', b'Friday'), (b'sat', b'Saturday'), (b'sun', b'Sunday')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dining_hall',
            field=models.CharField(choices=[(b'frank', b'Frank'), (b'frary', b'Frary'), (b'oldenborg', b'Oldenborg'), (b'scripps', b'Scripps'), (b'mudd', b'Mudd'), (b'cmc', b'CMC'), (b'pitzer', b'Pitzer')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.CharField(choices=[(b'breakfast', b'Breakfast'), (b'lunch', b'Lunch'), (b'dinner', b'Dinner'), (b'brunch', b'Brunch')], max_length=1024),
        ),
    ]
