# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagelist', '0002_booksale_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksale',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
