# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagelist', '0003_booksale_amazon_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksale',
            name='amazon_price',
        ),
        migrations.AddField(
            model_name='booksale',
            name='amazon_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
