# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagelist', '0005_auto_20160906_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksale',
            name='isbn',
            field=models.CharField(default='', max_length=20, verbose_name=b'ISBN'),
            preserve_default=False,
        ),
    ]
