# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagelist', '0006_auto_20160907_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksale',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
